import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";
import { canonicalHash } from "../src/canonical.ts";
import { validateLedger } from "../src/ledger.ts";
import { validateManifest } from "../src/manifest.ts";
import { narrateDiscrepancy, narrateReport, parseReportJson } from "../src/narrate.ts";
import { canonicalReport, recon, type Discrepancy, type Report } from "../src/recon.ts";

// Story 5.1 — the pure, deterministic explain-itself narration (AD-17). Every
// number/identifier the narration prints must be copied from real engine output
// (`report.discrepancies` / the tie-out axes); the template supplies only the
// sentence scaffolding, and none of it may enter the hashed bytes (AC-5.1.b).

const FIXTURES = join(import.meta.dirname, "..", "fixtures");

function fixtureText(kind: "slice" | "golden", name: string): string {
  return readFileSync(join(FIXTURES, kind, name), "utf8");
}

/** Re-derive the committed report from its manifest + ledger (the real engine
 * path the fixtures were generated by), so the narration is tested against a
 * genuine `Report`, not a hand-built object. */
function reconOf(kind: "slice" | "golden"): { report: Report; reportHash: string } {
  const manifest = validateManifest(JSON.parse(fixtureText(kind, "manifest.json")));
  assert.equal(manifest.ok, true, `${kind} manifest must validate`);
  if (!manifest.ok) throw new Error("unreachable");
  const ledger = validateLedger(JSON.parse(fixtureText(kind, "ledger.json")));
  assert.equal(ledger.ok, true, `${kind} ledger must validate`);
  if (!ledger.ok) throw new Error("unreachable");
  const result = recon(manifest.value, ledger.value);
  assert.equal(result.ok, true, `${kind} recon must succeed`);
  if (!result.ok) throw new Error("unreachable");
  return result.value;
}

test("AC-5.1.a — the slice narration names the exact breaking event (txHash, blockNumber, logIndex)", () => {
  const { report } = reconOf("slice");
  const narration = narrateReport(report);

  assert.equal(narration.status, "discrepancy");
  assert.equal(narration.discrepancies.length, 1);
  const reward = narration.discrepancies[0]!;
  assert.equal(reward.axis, "reward");

  // The named event is copied straight from report.discrepancies[].breakingEvent.
  const source = report.discrepancies[0]!.breakingEvent!;
  assert.equal(reward.breakingEvent?.txHash, source.txHash);
  assert.equal(reward.breakingEvent?.blockNumber, source.blockNumber);
  assert.equal(reward.breakingEvent?.logIndex, source.logIndex);

  // …and it is *named* in the human line (FR5): tx, block, logIndex all present.
  assert.match(reward.line, /0x5632e96c6acca45e7f081fb09e3d8fb1ee25ef8da58129503fbd1446cec04c98/);
  assert.match(reward.line, /block 25444795/);
  assert.match(reward.line, /logIndex 29/);
});

test("AC-5.1.b — the reward cause narrates as an unbooked rebase with the signed delta", () => {
  const { report } = reconOf("slice");
  const reward = narrateReport(report).discrepancies[0]!;

  // delta 1000000000 wei @ 18dp = 0.000000001 stETH, rendered with an explicit sign.
  assert.match(reward.line, /\+0\.000000001 stETH/);
  assert.match(reward.line, /reward rebase/);
  assert.match(reward.line, /not yet booked/);
  // The delta is echoed verbatim as a canonical fact (a bigint, not reformatted).
  assert.equal(reward.delta, report.discrepancies[0]!.delta);
});

test("AC-5.1.b — the golden report's reward discrepancy is narrated from its real event", () => {
  // NB: the golden fixture is NOT reconciled — its reward axis breaks by 0.5 stETH
  // by design (see recon.test.ts). The narration reports that real discrepancy,
  // never a hand-authored 'all clear'.
  const { report } = reconOf("golden");
  const narration = narrateReport(report);

  assert.equal(narration.status, "discrepancy");
  const reward = narration.discrepancies.find((d) => d.axis === "reward")!;
  assert.match(reward.line, /\+0\.5 stETH/);
  assert.match(reward.line, /block 21099000/);
  assert.match(reward.line, /logIndex 0/);
});

test("AC-5.1.b — a reconciled (empty-discrepancy) report narrates the always-green state", () => {
  const { report } = reconOf("golden");
  // Synthesize the everyday reconciled state by emptying discrepancies — the
  // narration path taken on any day the books tie out (no committed fixture ties
  // out, so this exercises the pure function directly).
  const reconciled: Report = { ...report, discrepancies: [] };
  const narration = narrateReport(reconciled);

  assert.equal(narration.status, "reconciled");
  assert.equal(narration.discrepancies.length, 0);
  assert.match(narration.headline, /reconciled/i);
  assert.match(narration.headline, /derivation reproduced/i); // honesty boundary (AD-16)
});

test("AC-5.1.a — narration is deterministic: the same report yields byte-identical output", () => {
  const { report } = reconOf("slice");
  const a = narrateReport(report);
  const b = narrateReport(report);
  // Structural + string equality across calls (bigint-safe stringify).
  const stamp = (r: Report) => JSON.stringify(narrateReport(r), (_k, v) => (typeof v === "bigint" ? `${v}` : v));
  assert.equal(stamp(report), stamp(report));
  assert.deepEqual(a.lines, b.lines);
});

test("breakingEvent === null is narrated honestly — no fabricated event", () => {
  const nullEvent: Discrepancy = { axis: "reward", delta: 7n, breakingEvent: null };
  const line = narrateDiscrepancy(nullEvent).line;
  // The delta is still named; NO block / tx / logIndex is invented.
  assert.doesNotMatch(line, /block \d/);
  assert.doesNotMatch(line, /logIndex/);
  assert.doesNotMatch(line, /0x[0-9a-f]{64}/);
  assert.match(line, /no in-window/i);
});

test("AC-5.1.b — narration is non-canonical: reportHash is unchanged and the report is not mutated", () => {
  const { report, reportHash } = reconOf("golden");
  const committed = fixtureText("golden", "reportHash.txt").trim();

  // Narration is presentational, so it never moves the hash: whatever the
  // committed golden reportHash is (0.2.0 fingerprint, post-remediation), it is
  // reproduced exactly here and below.
  assert.equal(reportHash, committed);
  assert.equal(reportHash, "0x1b20c27f07ff8495a9b33a6dab4d8b757ff2cf90bc9881bcd3eb1a927d20be1f");

  // Narrating reads but never mutates: the canonical hash is identical afterward.
  const before = canonicalHash(canonicalReport(report));
  narrateReport(report);
  const after = canonicalHash(canonicalReport(report));
  assert.equal(after, before);
  assert.equal(after, committed);
});

test("parseReportJson hydrates a committed report.json into the exact engine Report", () => {
  // The web loads report.json (canonical string-encoded bigints) as a static
  // asset; parseReportJson must invert canonicalReport back to the bigint Report
  // the narration consumes — proven by deep-equality with the engine's own output.
  for (const kind of ["slice", "golden"] as const) {
    const { report } = reconOf(kind);
    const hydrated = parseReportJson(JSON.parse(fixtureText(kind, "report.json")));
    assert.deepEqual(hydrated, report);
    // And the narration of the hydrated report equals the narration of the engine report.
    assert.deepEqual(narrateReport(hydrated), narrateReport(report));
  }
});

test("parseReportJson rejects a malformed report (a JSON-number where a decimal string is required)", () => {
  const bad = JSON.parse(fixtureText("slice", "report.json")) as Record<string, unknown>;
  (bad["valuation"] as Record<string, unknown>)["currentValueUsd"] = 1659689; // JSON number, not a string
  assert.throws(() => parseReportJson(bad));
});
